---
openapi: 3.0.0
info:
  title: Go United
  version: "0.1"
paths:
  /certificates:
    get:
      description: Returns certificates of a user
      parameters:
      - name: userId
        in: query
        description: ID of user to get certificates
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: List of certificates.
          content:
            application/json: {}
  /profile:
    get:
      description: Returns User data
      responses:
        "200":
          description: User data
          content:
            application/json: {}
components: {}
